
export const administrativePosts = {
  // cabo delgado
  Ancuabe: ["Ancuabe", "Metoro", "Meza"],
  Balama: ["Balama", "Impiri", "Kwekwe", "Mavala"],
  Chiúre: ["Chiure", "Chiure Velho", "Katapua", "Mazeze", "Namogelia", "Ocua"],
  Ibo: ["Ibo", "Quirimba"],
  Macomia: ["Macomia", "Chai", "Mucojo", "Quiterajo"],
  Mecúfi: ["Mecufi", "Murrebue"],
  Meluco: ["Meluco", "Muaguide"],
  "Mocímboa da Praia": ["Mocimboa da Praia", "Diaca", "Mbau"],
  Montepuez: ["Montepuez", "Mapupulo", "Mirate", "Nairoto", "Namanhumir"],
  Mueda: ["Mueda", "Chapa", "Imbuho", "Negomano", "N'gapa"],
  Muidumbe: ["Muidumbe", "Chitunda", "Miteda"],
  Namuno: ["Namuno", "Hucula", "Machoca", "Meloco", "Ncumpe", "Luli"],
  Nangade: ["Nangade", "Ntamba"],
  Palma: ["Palma", "Olumbe", "Pundanhar", "Quionga"],
  Pemba: ["Pemba"],
  "Pemba-Metuge": ["Metuge", "Mieze"],
  Quissanga: ["Quissange", "Bilibiza", "Mahate"],

  // nampula
  Angoche: ["Angoche", "Aube", "Namaponda", "Boila-Nametoria"],
  Eráti: ["Namapa", "Alua", "Namiroa"],
  "Ilha de Moçambique": ["Ilha de Moçambique", "Lumbo"],
  Lalaua: ["Lalaua", "Meti"],
  Malema: ["Malema", "Chihulo", "Mutuali"],
  Meconta: ["Meconta", "Corrane", "Namialo", "7 de Abril"],
  Mecubúri: ["Mecubúri", "Milhana", "Muite", "Namina"],
  Memba: ["Memba", "Chipene", "Lurio", "Mazue"],
  Mogincual: ["Mogincual", "Quinga", "Chunga", "Quixaxe", "Liupo"],
  Mogovolas: ["Nametil", "Calipo", "Ilute", "Muatua", "Nanhupo"],
  Moma: ["Macone", "Chalaua", "Larde", "Mucuali"],
  Monapo: ["Monapo", "Itoculo", "Netia"],
  Mossuril: ["Mossuril", "Lunga", "Matibane"],
  Muecate: ["Muecate", "Imala", "Muculuone"],
  Murrupula: ["Murrupula", "Chinga", "Nehessine"],
  "Nacala Porto": ["Maiaia", "Mutiva", "Muanona"],
  "Nacala-a-Velha": ["Nacala-a-Velha", "Covo"],
  Nampula: [
    "Muatala",
    "Muhala",
    "Namikopo",
    "Napipine",
    "Natikire",
    "Urbano Central",
  ],
  Nacarôa: ["Nacarôa", "Intete", "Saua-Saua"],
  Rapale: ["Rapale", "Anchilo", "Mutivaze", "Namaita"],
  Ribaué: ["Ribaué", "Kunle", "Iapala"],

  // zambezia
  "Alto Molócuè": ["Alto Molócuè", "Nauela"],
  Chinde: ["Chinde", "Luabo", "Micaune"],
  Derre: ['Derre', 'Machimbo', 'Guerissa'],
  Gilé: ["Gilé", "Alto Lingonha"],
  Gurué: ["Gurué", "Lioma", "Nepuagiua"],
  Ile: ["Ile", "Mulevala", "Socone"],
  Inhassunge: ["Mucupia", "Gonhane"],
  Lugela: ["Lugela", "Tacuane", "Munhamade", "Muabanama"],
  "Maganja da Costa": ["Maganja da Costa", "Bojone", "Mocubela", "Nante"],
  Milange: ["Milange", "Majaua", "Molumbo", "Mongue"],
  Mocuba: ["Mocuba", "Mugeba", "Namajavira"],
  Mopeia: ["Mopeia", "Campo"],
  Morrumbala: ["Morrumbala", "Chire", "Megaza"],
  Namacurra: ["Namacurra", "Mucuse", "Namarroi", "Regone"],
  Nicoadala: ["Nicoadala", "Maquival"],
  Pebane: ["Pebane", "Mulela Mualama", "Naburi"],
  Quelimane: ['Quelimane']
};