export const districtsByProvince = {
  Nampula: [
    "Angoche",
    "Eráti",
    "Ilha de Moçambique",
    "Lalaua",
    "Larde",
    "Liúpo",
    "Malema",
    "Meconta",
    "Mecubúri",
    "Memba",
    "Mogincual",
    "Mogovolas",
    "Moma",
    "Monapo",
    "Mossuril",
    "Muecate",
    "Murrupula",
    "Nacala-a-Velha",
    "Nacala-Porto",
    "Nacarôa",
    "Nampula",
    "Rapale",
    "Ribáuè",
  ],
  "Cabo Delgado": [
    "Ancuabe",
    "Balama",
    "Chiúre",
    "Ibo",
    "Macomia",
    "Mecúfi",
    "Meluco",
    "Metuge",
    "Mocímboa da Praia",
    "Montepuez",
    "Mueda",
    "Muidumbe",
    "Namuno",
    "Nangade",
    "Palma",
    "Pemba",
    "Quissanga",
  ],
  Zambézia: [
    "Alto Molócuè",
    "Chinde",
    "Derre",
    "Gilé",
    "Gurué",
    "Ile",
    "Inhassunge",
    "Luabo",
    "Lugela",
    "Maganja da Costa",
    "Milange",
    "Mocuba",
    "Mocubela",
    "Molumbo",
    "Mopeia",
    "Morrumbala",
    "Mulevala",
    "Namacurra",
    "Namarroi",
    "Nicoadala",
    "Pebane",
    "Quelimane",
  ],
};