import React, { useState, useEffect, useRef } from 'react'
import {
  Dashboard,
  Forest,
  LegendToggle,
  PersonAdd,
  LocationOn,
  Group,
} from "@mui/icons-material";
import { Avatar, BottomNavigation, BottomNavigationAction, Box, CssBaseline, List, ListItem, ListItemAvatar, ListItemText, Paper } from "@mui/material";

function refreshMessages() {
  const getRandomInt = (max) => Math.floor(Math.random() * Math.floor(max));

  return Array.from(new Array(50)).map(
    () => messageExamples[getRandomInt(messageExamples.length)]
  );
}


const styledBottomNavigation = {
  "& .Mui-selected": {
    color: "rebeccapurple",
  },
  "&	.MuiIcon-colorAction": {
    color: "rebeccapurple",
  }
}


const Footer = () => {

 const [value, setValue] = useState(0);
 const ref = useRef(null);
 const [messages, setMessages] = useState(() => refreshMessages());

 useEffect(() => {
   ref.current.ownerDocument.body.scrollTop = 0;
   setMessages(refreshMessages());
 }, [value, setMessages]);



  return (
    <Box sx={{ pb: 7, display: { xs: "block", sm: "none" } }} ref={ref}>
      <CssBaseline />
      <List>
        {messages.map(({ primary, secondary, person }, index) => (
          <ListItem button key={index + person}>
            <ListItemAvatar>
              <Avatar alt="Profile Picture" src={person} />
            </ListItemAvatar>
            <ListItemText primary={primary} secondary={secondary} />
          </ListItem>
        ))}
      </List>
      <Paper
        sx={{ position: "fixed", bottom: 0, left: 0, right: 0 }}
        elevation={3}
      >
        <BottomNavigation
        sx={styledBottomNavigation}
          showLabels
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
          <BottomNavigationAction label="Meu Painel" icon={<Dashboard />} />
          <BottomNavigationAction label="Monitoria" icon={<LegendToggle />} />
          <BottomNavigationAction label="Produtores" icon={<Group />} />
          <BottomNavigationAction label="Pomares" icon={<Forest />} />
        </BottomNavigation>
      </Paper>
    </Box>
  );
};

const messageExamples = [
  {
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
  },
  {
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
  },
  {
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
  },
  {
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
  },
  {
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
  },
  {
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
  },
  {
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
  },
];

export default Footer;
